fix: ❌ No changes detected after adding files Git status: HEAD detached at pull/5/merge Changes not staged for commit:   (use "git add <file>..." to update what will be committed)   (use "git restore <file>..." to discard changes in working directory) 	modified:   sites/every-noise/site.yml
Untracked files:
  (use "git add <file>..." to include in what will be committed)
	.github/generated_sites.txt

no changes added to commit (use "git add" and/or "git commit -a")
Checking if files were modified:
Error: Process completed with exit code 1.